### ISSUE TITLE
standardize name in subject line?

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/ds-hurricanes-monitoring#4]
I think it would be good if the beginning of the subject line could be standardized with "Hurricane Monitoring:" or something like that for english + the equivalent for French. 

I noticed they are not standardized when I tried to create a rule to send these to a specific folder in my email :-)

**Comment by t-downing** [comment]
Good point! For the Haiti ones I'm going to keep them the same, since it's for the framework and the email format is included in the framework document (and they always start with "Action anticipatoire Haïti" anyways). But for these ones, I've set the format to:

Hurricane Monitoring [`Caribbean / Havana`]: `storm name` forecast issued `issue time`, `issue date`

I also changed the specifier to "Havana" (admin1) because that's what we're actually monitoring.

5de76f4bf094928f44eaabfdb65e7e50e9dc9bb9
